### ISSUE TITLE
[REQ] Add Ranks in Config

### ISSUE THREAD

**Issue by Mihale0309** [KitsuneLab-Development/K4-Zenith#13]
Can we get rank configuration in the "K4-Zenith-Ranks.yaml" and not be hardstuck in the code? (Like let them change how many points for Silver I, II, III, etc) Many people maybe don't know if they can modify them or don't know how? It would be cool

**Comment by K4ryuu** [comment]
When you start the ranks module first, it logs that it created the ranks.jsonc file. This file let you edit the points and ranks obviously, as in K4-System.
