### ISSUE TITLE
[REQ]  TIme based IP BANS

### ISSUE THREAD

**Issue by rcon420** [KitsuneLab-Development/K4-Zenith#16]
Hi, consider making time based IP Bans for example I set in the settings IP bans after being issued  expire in  5 days Would help a lot tempory to avoid cases when player is changing accounts and it would prevent  a lot of false ip bans

**Comment by K4ryuu** [comment]
Greetings,
Ip bans not recommended to use. The reason is in the config description.

**Comment by K4ryuu** [comment]
Using IP bans are possible by enabling in the config.
Separated IP ban is not planned for now due to IP-bans cannot be used that much anymore due to Cloud Gamings.
