### ISSUE TITLE
[BUG] MinPlayers in Zenith-Ranks

### ISSUE THREAD

**Issue by tdziero** [KitsuneLab-Development/K4-Zenith#17]
in the latest version there is a problem with 'MinPlayers', the value is not changed and shows all the time from 4 players

**Comment by K4ryuu** [comment]
Greetings,
I've checked the issue, and I see no issue with any of the config validations. Make sure you change only current values and always use latest builds.

![CleanShot 2024-09-17 at 17 57 01@2x](https://github.com/user-attachments/assets/5cab4921-2140-4267-842e-22ecc6a13b3c)
