### ISSUE TITLE
k4 system

### ISSUE THREAD

**Issue by gha241** [KitsuneLab-Development/K4-Zenith#18]
How do I turn off rank advancement, I only want points
 k4 system

**Comment by K4ryuu** [comment]
Greetings,
This is Zenith's Github page, not K4-System.

Also what do you mean by "rank advancements"?

**Comment by gha241** [comment]
What I mean is that I have prime points set and I still get promoted to CS GO rank. Can I turn this off somehow?

**Comment by K4ryuu** [comment]
Added global option (to configs) for this to the upcoming release (1.0.18).
Thank you for the idea!
