### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by zeroxissk** [KitsuneLab-Development/K4-Zenith#19]
![image](https://github.com/user-attachments/assets/34237c8b-8ffa-442a-a8a6-ba8de7ede22b)

LOG
{"MVP": 3, "Kills": 16, "Deaths": 16, "Shoots": 436, "Assists": 9, "GameWin": 1, "RoundsT": 0, "GameLose": 0, "GearHits": 0, "Grenades": 55, "HeadHits": 10, "NeckHits": 0, "RoundWin": 0, "RoundsCT": 0, "ChestHits": 20, "Headshots": 7, "HitsGiven": 61, "HitsTaken": 94, "RoundLose": 0, "FirstBlood": 3, "UnusedHits": 0, "AssistFlash": 1, "BombDefused": 2, "BombPlanted": 2, "FlashedKill": 0, "LeftArmHits": 0, "LeftLegHits": 1, "NoScopeKill": 0, "RevengeKill": 0, "SpecialHits": 0, "StomachHits": 5, "RightArmHits": 4, "RightLegHits": 3, "DominatedKill": 0, "HostageKilled": 0, "RoundsOverall": 25, "ThruSmokeKill": 2, "HostageRescued": 0, "PenetratedKill": 2} - R CT = 0 , R T =0
I redid the server installation, that is, there is no k4-sytem installed, only Zenith, and it does not count the CT and TR rounds, is there any way to solve this, or do you have to use the 2 plugins to work both k4 when the zenith

**Comment by zeroxissk** [comment]
Complementing.

I installed mysql and the server without k4-sytem, ​​because I thought there might be some incompatibility, I'm using the latest plugin where it says that this error is corrected, but if we check the database, it doesn't capture this information for some reason , we can say that maybe on the server the counterstrikeshap is old or MATHCZY pug plugin is incompatible, well I don't know, but here it doesn't work and I've tried everything :D

**Comment by K4ryuu** [comment]
Greetings,
A symbol was missing from the spawn validation (which let only user counted who spawned in the round), so the round stats were not counter properly. I've fixed this issue now, and going to be pushed with next upcoming (1.0.19) release.

Thank you for the feedback!

**Comment by zeroxissk** [comment]
Thank you very much for your feedback, I'll be waiting for the UPDATE, that's why you guys are BEAUTIFUL, the best plugin package there is :D
