### ISSUE TITLE
[BUG] Module Zenith-Ranks need "FollowCS2ServerGuidelines" to turn False ?

### ISSUE THREAD

**Issue by BigTwoProduction** [KitsuneLab-Development/K4-Zenith#22]
Hello,

I use before K4 And now switch to Zenith.
Before a never set "FollowCS2ServerGuidelines" to false.
But now if "FollowCS2ServerGuidelines" is True there is a lot of error coming to log.

Did Zenith-Ranks module need FollowCS2ServerGuidelines to turn false in counterstrikesharp core.json ?
This is a requirements ?

Exemple of error.
![image](https://github.com/user-attachments/assets/c3523659-1ce6-4752-8f6d-c9ebc2b1595c)

Best regards,
Jordan.

**Comment by gha241** [comment]
Set FollowCS2ServerGuidelines on false

**Comment by BigTwoProduction** [comment]
Hello, yes i know and i already do that.
But there a way to disable an option in K4-Zenith-Ranks.yaml to works with FollowCS2ServerGuidelines = true.

Or there is a strict requirements to FollowCS2ServerGuidelines set as false ?

Best regard,
Jordan.

**Comment by K4ryuu** [comment]
It's as strict to follow if you use fake ranks on the tab.
