### ISSUE TITLE
[BUG] Ghost Bug

### ISSUE THREAD

**Issue by ItsCEED** [KitsuneLab-Development/K4-Zenith#9]
You are becoming invisible.

Repro:
> !team target spec
> !team target ct/tt
> it wont spawn you so you have to force spawn
> !respawn target

you are now ghost.

**Comment by K4ryuu** [comment]
ToDo: Validate and check all extended commands

**Comment by K4ryuu** [comment]
The issue has been resolved in the upcoming release.
Thank you for the report!
